version: '3.8'

services:
  sum-api:
    build: .
    container_name: sum-hierarchical-engine
    ports:
      - "3000:3000"    # Flask API server
      - "8765:8765"    # Progressive Summarization WebSocket
    volumes:
      - ./uploads:/app/uploads          # File uploads
      - ./Output:/app/Output            # Processing outputs
      - ./Data:/app/Data                # Data storage
      - ./temp:/app/temp                # Temporary files
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=3000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - sum-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: sum-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates (if available)
    depends_on:
      - sum-api
    restart: unless-stopped
    networks:
      - sum-network
    profiles:
      - production  # Only start with: docker-compose --profile production up

networks:
  sum-network:
    driver: bridge
    name: sum-hierarchical-network

volumes:
  sum-data:
    name: sum-persistent-data
  sum-outputs:
    name: sum-processing-outputs