version: '3.8'

services:
  sum:
    build: .
    container_name: sum-app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change-this-in-production
    volumes:
      - ./uploads:/app/uploads
      - ./Output:/app/Output
    restart: unless-stopped

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: sum-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: