// Render receipt signing — Phase E.1 v0.9.A.
//
// Each /api/render response carries a `render_receipt` block: a
// detached JWS (RFC 7515 §A.5) with EdDSA / Ed25519 signature over
// the JCS-canonicalised payload (RFC 8785). Consumers can:
//
//   1. Fetch the public key from /.well-known/jwks.json (RFC 7517).
//   2. JCS-canonicalise the receipt's `payload` object.
//   3. Verify with `jose.flattenedVerify` against the JWK whose
//      `kid` matches the receipt's `kid`.
//
// The receipt attests "this Worker rendered this tome from these
// triples at these slider positions at this time." It does NOT
// attest factual truth of the tome — that's what the Python bench
// + NLI audit verifies separately. The `digital_source_type` field
// uses C2PA terminology (`trainedAlgorithmicMedia`) so consumers
// know unambiguously the tome is AI-generated.

import { CompactSign, importJWK, type JWK } from "jose";
import canonicalize from "canonicalize";

export const RECEIPT_SCHEMA = "sum.render_receipt.v1";
// C2PA digitalSourceType taxonomy (spec.c2pa.org v2.2):
//   trainedAlgorithmicMedia — generated by an AI model (LLM render path).
//   algorithmicMedia        — generated by a deterministic algorithm
//                             (canonical-path render: pure prose
//                             composition from facts, no model).
export const DIGITAL_SOURCE_TYPE_AI = "trainedAlgorithmicMedia";
export const DIGITAL_SOURCE_TYPE_DETERMINISTIC = "algorithmicMedia";

export type DigitalSourceType =
  | typeof DIGITAL_SOURCE_TYPE_AI
  | typeof DIGITAL_SOURCE_TYPE_DETERMINISTIC;

export type Provider =
  | "anthropic"
  | "openai"
  | "cf-ai-gateway-anthropic"
  | "canonical-path";

export interface ReceiptPayload {
  render_id: string;
  sliders_quantized: {
    density: number;
    length: number;
    formality: number;
    audience: number;
    perspective: number;
  };
  triples_hash: string;
  tome_hash: string;
  /** What actually served the call. The API's reported model (which
   *  may resolve to a more specific snapshot than the requested tag);
   *  for canonical-path renders, the literal string
   *  "canonical-deterministic-v0". Receipt signs THIS value. */
  model: string;
  /** Concrete provider that produced the tome. Lets verifiers
   *  distinguish AI providers, gateways, and the canonical path. */
  provider: Provider;
  signed_at: string;
  digital_source_type: DigitalSourceType;
}

export interface RenderReceipt {
  schema: typeof RECEIPT_SCHEMA;
  kid: string;
  payload: ReceiptPayload;
  jws: string;
}

/** Hex-encoded sha256 of the input bytes, prefixed `sha256-`. */
async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", bytes);
  return (
    "sha256-" +
    Array.from(new Uint8Array(buf))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("")
  );
}

export async function hashTriples(
  triples: Array<[string, string, string]>,
): Promise<string> {
  // Componentwise tuple-lex sort, then JCS canonicalisation.
  // Matches Python's `sorted(tuple(t) for t in triples)` byte-for-byte
  // even when triple components contain separator-like characters
  // (e.g., '|'). Earlier draft used a `${a[0]}||${a[1]}||${a[2]}`
  // join-sort which diverged from Python's default tuple ordering
  // on inputs like `[["a||b","x","y"], ["a","b","y"]]` — the join
  // leaks rightmost component bytes into the leftmost comparison
  // space. Componentwise comparison fixes this without losing
  // determinism. v0.9.A.1 review-pass fix.
  const sorted = [...triples].sort((a, b) => {
    for (let i = 0; i < 3; i++) {
      if (a[i] < b[i]) return -1;
      if (a[i] > b[i]) return 1;
    }
    return 0;
  });
  const canonical = canonicalize(sorted);
  if (typeof canonical !== "string") throw new Error("canonicalize returned undefined");
  return sha256Hex(new TextEncoder().encode(canonical));
}

export async function hashTome(tome: string): Promise<string> {
  return sha256Hex(new TextEncoder().encode(tome));
}

/**
 * Sign the receipt payload with the Worker's signing JWK. Returns
 * the receipt block ready to embed in the /api/render response.
 *
 * The JWS is detached: protected header `{alg, kid, b64: false,
 * crit: ['b64']}`, empty middle segment, signature segment carries
 * Ed25519 over the JCS-canonical bytes of `payload`. Consumers
 * verify by re-canonicalising `payload` from the response they
 * received and calling `jose.flattenedVerify({protected, payload,
 * signature})` against the matching JWK from /.well-known/jwks.json.
 */
export async function signReceipt(
  payload: ReceiptPayload,
  signingJWK: JWK,
  kid: string,
): Promise<RenderReceipt> {
  const key = await importJWK(signingJWK, "EdDSA");
  const canonicalStr = canonicalize(payload);
  if (typeof canonicalStr !== "string") {
    throw new Error("canonicalize returned undefined for payload");
  }
  const canonicalBytes = new TextEncoder().encode(canonicalStr);
  const jws = await new CompactSign(canonicalBytes)
    .setProtectedHeader({ alg: "EdDSA", kid, b64: false, crit: ["b64"] })
    .sign(key);
  return { schema: RECEIPT_SCHEMA, kid, payload, jws };
}
