"""
knowledge_os.py - Knowledge Operating System API

Implements the Knowledge OS endpoints for thought capture, density, and retrieval.
Integrates with the main SUM ecosystem.

Author: ototao
License: Apache License 2.0
"""

from flask import Blueprint, jsonify, request
import time
import json
import os
import random

knowledge_bp = Blueprint('knowledge_os', __name__)

# --- In-Memory Storage (Mock for MVP) ---
# In a real implementation, this would connect to SQLite/Postgres
THOUGHTS_STORE = []

# --- Helper Functions ---

def generate_insights():
    """Generate mock insights based on stored thoughts."""
    if not THOUGHTS_STORE:
        return ["Start capturing your thoughts to see insights here."]
    
    count = len(THOUGHTS_STORE)
    return [
        f"You have captured {count} thoughts so far.",
        "Your thinking patterns show a focus on productivity.",
        "Consider connecting your recent ideas on AI with your goals."
    ]

def get_contextual_prompt():
    """Return a prompt based on time of day or random selection."""
    prompts = [
        "What's on your mind right now?",
        "What was the most important thing you learned today?",
        "What problem are you trying to solve?",
        "Capture a fleeting idea before it's gone.",
        "Reflect on your current focus."
    ]
    return random.choice(prompts)

# --- Routes ---

@knowledge_bp.route('/knowledge', methods=['GET'])
def knowledge_index():
    """Main Knowledge OS status/info."""
    return jsonify({
        'status': 'active',
        'version': '1.0.0',
        'thought_count': len(THOUGHTS_STORE),
        'mode': 'knowledge_os'
    })

@knowledge_bp.route('/knowledge/capture', methods=['POST'])
def capture_thought():
    """
    Capture a thought.
    Payload: { "content": "My thought...", "tags": ["tag1"] }
    """
    try:
        data = request.get_json()
        if not data or 'content' not in data:
            return jsonify({'error': 'Content is required'}), 400
        
        thought = {
            'id': f"th_{int(time.time()*1000)}",
            'content': data['content'],
            'tags': data.get('tags', []),
            'timestamp': time.time(),
            'processed': False 
        }
        
        # Simulate "Invisible Intelligence" processing
        # In real app, this would be async background task
        thought['processed'] = True
        thought['enriched_context'] = "Context auto-generated by AI"
        
        THOUGHTS_STORE.append(thought)
        
        return jsonify({
            'success': True,
            'thought': thought,
            'message': 'Thought captured and enriched'
        }), 201

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@knowledge_bp.route('/knowledge/recent-thoughts', methods=['GET'])
def recent_thoughts():
    """Retrieve recent thoughts."""
    limit = int(request.args.get('limit', 10))
    # Return last N thoughts, reversed (newest first)
    return jsonify(THOUGHTS_STORE[-limit:][::-1])

@knowledge_bp.route('/knowledge/prompt', methods=['GET'])
def get_prompt():
    """Get a contextual prompt for the user."""
    return jsonify({
        'prompt': get_contextual_prompt()
    })

@knowledge_bp.route('/knowledge/insights', methods=['GET'])
def get_insights():
    """Get system insights about thinking patterns."""
    return jsonify({
        'insights': generate_insights()
    })

@knowledge_bp.route('/knowledge/densify', methods=['GET'])
def check_densification():
    """
    Check if densification (compression of thoughts) is needed/available.
    """
    # Simple logic: if more than 5 thoughts, suggest densification
    needs_density = len(THOUGHTS_STORE) > 5
    return jsonify({
        'status': 'available' if needs_density else 'waiting',
        'message': 'Ready to compress insights' if needs_density else 'More thoughts needed',
        'thought_count': len(THOUGHTS_STORE),
        'threshold': 5
    })

@knowledge_bp.route('/knowledge/densify/<concept>', methods=['POST'])
def perform_densification(concept):
    """
    Perform densification on a specific concept.
    """
    # Mock densification logic
    relevant_thoughts = [t for t in THOUGHTS_STORE if concept.lower() in t['content'].lower()]
    
    return jsonify({
        'concept': concept,
        'densified_summary': f"Synthesized wisdom regarding '{concept}' from {len(relevant_thoughts)} thoughts.",
        'source_count': len(relevant_thoughts)
    })
