"""Deterministic-judge probe runner — generate or check the committed
cross-architecture decision expectations.

Modes:
  --write   Run the selected judge modes (default: float32-det) on the
            committed probe set and (over)write expected_decisions.json,
            stamped with the generating environment. Run this ONLY on the
            machine whose results you intend to commit as the reference.
  --check   Recompute the selected modes on THIS machine and compare against
            the committed expectations: every decisively-margined pair must
            reproduce its decision (exit 1 otherwise); near-threshold pairs
            and margin drift are reported, not gated. This is what the
            monthly judge-smoke CI canary runs on x86_64 against the
            committed arm64 expectations — the cross-architecture
            decision-agreement MEASUREMENT.

Requires the [judge] extra + the pinned models (downloads on first use).
See sum_engine_internal/research/meaning/deterministic_judge.py for the
honest boundary this measures.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from sum_engine_internal.research.meaning.deterministic_judge import (  # noqa: E402
    EXPECTED_PATH,
    MARGIN_DECISIVE_MICRO,
    PROBE_SET_PATH,
    DeterministicNLIJudge,
    compare_probe_results,
    decisions_digest,
    run_probe,
)

# float32-det is the shipped deterministic mode and the only one committed
# to expected_decisions.json / gated in CI. int8-det is an EXPERIMENT flag:
# measured 2026-07-10 (torch 2.7.1, qnnpack, arm64), naive dynamic INT8
# collapses the judge (11/22 decisions flip, every entailment lost) — see
# the module docstring in deterministic_judge.py. Pass --modes to probe it.
DEFAULT_MODES = ("float32-det",)


def _judge_for(mode: str, threshold: float) -> DeterministicNLIJudge:
    return DeterministicNLIJudge(
        threshold=threshold, quantize="int8" if mode == "int8-det" else None
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    ap.add_argument("--probe", default=str(REPO / PROBE_SET_PATH))
    ap.add_argument("--expected", default=str(REPO / EXPECTED_PATH))
    ap.add_argument(
        "--modes", nargs="+", default=list(DEFAULT_MODES),
        choices=["float32-det", "int8-det"],
        help="judge modes to probe (default: the shipped float32-det only)",
    )
    args = ap.parse_args()
    modes = tuple(args.modes)

    probe = json.loads(Path(args.probe).read_text())
    pairs, threshold = probe["pairs"], float(probe["threshold"])

    if args.write:
        doc: dict = {"what_this_is": (
            "Committed reference decisions for the deterministic-judge "
            "probe. Generated by scripts/research/deterministic_judge_probe.py "
            "--write on the environment recorded per mode below. The "
            "judge-smoke CI canary recomputes these on its own architecture "
            "and gates on decisive-pair agreement."
        ), "threshold": threshold, "modes": {}}
        for mode in modes:
            judge = _judge_for(mode, threshold)
            results = run_probe(judge, pairs)
            doc["modes"][mode] = {
                "environment": judge.environment,
                "decisions_digest": decisions_digest(results),
                "results": results,
            }
            print(f"[{mode}] {len(results)} pairs, "
                  f"digest {doc['modes'][mode]['decisions_digest'][:19]}…, "
                  f"env {judge.environment}", file=sys.stderr)
        Path(args.expected).write_text(json.dumps(doc, indent=1) + "\n")
        print(f"wrote {args.expected}", file=sys.stderr)
        return 0

    expected_doc = json.loads(Path(args.expected).read_text())
    assert float(expected_doc["threshold"]) == threshold, "threshold drift"
    all_ok = True
    for mode in modes:
        exp = expected_doc["modes"][mode]
        judge = _judge_for(mode, threshold)
        actual = run_probe(judge, pairs)
        report = compare_probe_results(
            exp["results"], actual,
            decisive_margin_micro=MARGIN_DECISIVE_MICRO,
        )
        report["mode"] = mode
        report["expected_environment"] = exp["environment"]
        report["actual_environment"] = judge.environment
        # The near-threshold + drift detail matters more on divergence;
        # keep the always-printed summary compact.
        summary = {
            k: report[k]
            for k in (
                "mode", "n_pairs", "n_decisive", "n_near_threshold",
                "decisive_agreement", "max_abs_margin_drift_micro",
            )
        }
        print(json.dumps(summary))
        if not report["decisive_agreement"]:
            all_ok = False
            print(
                f"[{mode}] DECISIVE DISAGREEMENT — cross-architecture "
                f"decision stability FAILED on:", file=sys.stderr,
            )
            print(json.dumps(report["disagreements"], indent=1),
                  file=sys.stderr)
        if report["near_threshold"]:
            print(
                f"[{mode}] near-threshold pairs (reported, not gated): "
                f"{[e['index'] for e in report['near_threshold']]}",
                file=sys.stderr,
            )
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
